### PR TITLE
Translation for Simplified Chinese.

### PR DESCRIPTION
**Pull request by Sigmenzzz**

### CODE REVIEW

**Comment by Traister101** [comment]
Oh nice! Just so you know the current dev/1.20 branch has a couple new items/Lang changes. I don't think anything else will be added till after the next release so probably makes sense to do those as well. Could do it in this PR or make a separate one. Whatever suits you.

**Comment by Traister101** [comment]
Oh, actually scratch that I'll probably be adding a couple more achievements or just generally fiddle with them some more. I'll try remember to ping you once dev stuff is merged, or just come in here and make another PR after the mod gets another release

**Comment by Sigmenzzz** [comment]
ok,I'll wait for it

**Comment by Traister101** [comment]
Hey, the dev/1.20 branch is going to get merged likely within a couple days. I'll pretty confidently say that the lang is finalized so it's safe to translate the stuff there. Can close or rebase the PR either works

**Pull request closed without merging**
